_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.1
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
architecture:
    value: transformer
dataset_id:
    value: ultrachat_200kp0.1_seed42_level2_rare
learning_rate:
    value: 0.0002
